### ISSUE TITLE
Restructure Laundry Endpoints

### ISSUE THREAD

**Issue by joshdoman** [pennlabs/penn-sdk-python#101]
Scraping the full http://suds.kite.upenn.edu/ every 30 seconds and storing results in Redis will allow for faster loading times on iOS and allow us to quickly return an arbitrary number of rooms. We should also bring together current status and usage data into a single laundry endpoint 
```laundry/rooms?ids=1,31,35,... ```

It should have the following structure:

```
{ “rooms”: [{
	“id”: 1,
	“name”: “Bishop White”,
	“location”: “Quad”,
	"machines": [
		"id": 1, 
		"status": "End of cycle", 
		"time_remaining": 15, 
		"type": "dryer"
		}, 
		{
		"id": 1, 
		"status": "Available”, 
		"time_remaining": 0, 
		"type": "washer"
		}, 
		…
		],
	“usage_data”: {
		"day_of_week": "Friday", 
  		"dryer_data": {
    			"0": 2.5, 
    			"1": 2.85, 
    			"2": 2.85, 
    			"3": 2.65, 
    			"4": 2.7, 
			…
			"25": 2.813, 
    			"26": 2.875
  		}, 
  		"end_date": "2018-03-02", 
  		"hall_name": "Harrison Floor 24", 
  		"location": "Harrison", 
  		"start_date": "2018-02-02", 
  		"total_number_of_dryers": 3.0, 
  		"total_number_of_washers": 3.0, 
  		"washer_data": {
    			"0": 2.5, 
    			"1": 2.85, 
    			"2": 2.85, 
    			"3": 2.65, 
    			"4": 2.7, 
			…
			"25": 2.813, 
    			"26": 2.875
  		}
	},
	{
		“id”: 2,
		“name”: “Magee”,
		“location”: “Quad”,
		…
	},
	…
	]
}
```

**Comment by joshdoman** [comment]
@ymann how close is what you are working on to this?

**Comment by ymann** [comment]
It’s literally this plus adding a couple new endpoints.

**Comment by joshdoman** [comment]
@ymann Sweet! What are the new endpoints you're working? And will this be difficult to implement? It's mainly just combining the usage and hall endpoints into one.

**Comment by ymann** [comment]
Getting individual hall data, moving some data the mobile us over to the sdk (maybe will need a bit more work). It shouldn’t be difficult at all, I’ll submit a pull request before we get back from break.

**Comment by joshdoman** [comment]
Why are we moving mobile data over to the SDK? Doesn't laundry usage data need to be stored in the server's DB?

**Comment by ymann** [comment]
Not mobile data. Laundry usage is currently being stored on the mobile server, it’d be nice if we could give everyone access to it.

**Comment by joshdoman** [comment]
Let me move this issue to penn-mobile-server.

**Comment by joshdoman** [comment]
Closing this issue because moving it to penn-mobile-server.
