### ISSUE TITLE
Querying during data reload 

### ISSUE THREAD

**Issue by feefles** [pennlabs/penn-sdk-python#48]
Querying when Penn InTouch is doing the warehouse data reload (which is nightly) hits the raise ValueError in base.py. I think either you should a) update docs to add this is a possibility or maybe warn users that this happens and/or
b) potentially add some argument that says retry query until success for this specific error... 

Not sure what your desired behavior would be, but I'd be happy to implement either option once I hear your input.

**Comment by adelq** [comment]
That's an excellent point. For now, we should definitely add this to the docs here and on pennlabs/penn-sdk-node and pennlabs/penn-sdk-ruby.
What is the error exactly? If it's a unique error, we can also throw a custom exception. Retrying won't be effective simply because it's not an intermittent error to my knowledge, but at least that way projects that use the SDK can catch the error and try an hour later.

**Comment by feefles** [comment]
Traceback (most recent call last):
  File "autoregister.py", line 38, in <module>
    r = reg.section(...)
  File "/usr/local/lib/python2.7/dist-packages/penn/registrar.py", line 72, in section
    return next(sections)
  File "/usr/local/lib/python2.7/dist-packages/penn/registrar.py", line 32, in _iter_response
    response = self._request(url, params)
  File "/usr/local/lib/python2.7/dist-packages/penn/base.py", line 28, in _request
    raise ValueError(response['service_meta']['error_text'])
ValueError: The application is refreshing data, usage is not currently allowed, please try again shortly.

**Comment by adelq** [comment]
So it looks like the error given is fairly descriptive, but `ValueError` doesn't seem appropriate. I'll put in a few changes to documentation and how errors are handled, and we'll work off of those to see if they adequately fix this issue.

**Comment by adelq** [comment]
@feefles can you check out the pull request and see if that resolves the problem for you?

**Comment by feefles** [comment]
The changes look good to me. I'll let you know if there are any errors. Thanks!

**Comment by adelq** [comment]
Yup! Thanks for your help, just reopen the issue with more details if it's still buggy or frustrating.
